language: ruby
rvm:
  - 2.2.2
  - 2.3.0
  - 2.4.1
gemfile:
  - gemfiles/Gemfile.mongoid-6
  - gemfiles/Gemfile.mongoid-7
  - gemfiles/Gemfile.mongoid-8
  - gemfiles/Gemfile.mongoid-9
  - Gemfile
services:
  - mongodb
sudo: false