language: ruby
rvm:
  - rbx-19mode
  - jruby-19mode
  - 1.9.2
  - 1.9.3
  - 2.1.0
  - ruby-head
  - jruby-head
gemfile:
  - gemfiles/Gemfile.mongoid-3.0
  - gemfiles/Gemfile.mongoid-4.0
  - Gemfile
services:
  - mongodb